### ISSUE TITLE
is there a way to contribute to improve your training dictionaries

### ISSUE THREAD

**Issue by Motorrat** [Babylonpartners/fastText_multilingual#1]
Of course just the fact that you made it so far with purely automated translation is amazing! Could we try to get you even better training database by manually vetting your 10K lists? I could check en, ru, de, es in any combination, for example.

**Comment by sls56** [comment]
Cheers Motorrat!
I think there's a lot more we could do on the methods side to improve the alignment. I wouldn't want to use up people's time before doing some more work myself!

We would like to open source the training/test dictionaries, but we haven't done so yet since we aren't completely sure legally whether the Google Translate API allows this. We're going to try to find out though!

**Comment by AjayTalati** [comment]
Hi Samuel,

any chance you can release just a few of the training/test dictionaries? I guess you might have some non Google dicts that you probably have used for calculating the matrices? 

Would be really nice to be able to go through and reproduce the calculations in your paper with real data. Who knows? Maybe someone else might find alternative methods :)

All the best,

Ajay

**Comment by sls56** [comment]
Hi Ajay,

All the training/test dictionaries for the matrices in this repository were constructed from Google Translate, but the training/test dictionaries and the word vectors for English and Italian used in our paper are all freely available online from this link:
http://clic.cimec.unitn.it/~georgiana.dinu/down/

When we get back from holiday next week we'll investigate open-sourcing the dictionaries used in this repository, and we will also provide some training code (it was just a rush getting the repository out before the ICLR conference...). We are definitely keen to see people improve on our work :)

Best wishes,
Sam

**Comment by AjayTalati** [comment]
Thank you :)
