### ISSUE TITLE
Trying to find a vector for a hindi word using this library fails.

### ISSUE THREAD

**Issue by gvishal** [Babylonpartners/fastText_multilingual#10]
I loaded the hindi fast text trained vectors provided by facebook. It works find when I use gensim, but when I use this library to retrieve a vector for any hindi word it says not found. I can see that hindi words are present in the dictionary but it is unable to retrieve. 

I am guessing some encoding issues. So, I digged deeper and found that words in the dictionary are stored in string format and not unicode, resulting in hindi words not being found. Is there a easy fix for this?

```python
hi_dictionary = FastVector(vector_file=embedding_file1+'.vec')
```

    reading word vectors from /home/jaspreet/vg/datasets/embeddings/wiki.hi.vec

```python
for word in hi_dictionary.word2id:
    print word, type(word)
    break
```

    fawn <type 'str'>

**Comment by gvishal** [comment]
Fixed it by adding below here: https://github.com/Babylonpartners/fastText_multilingual/blob/master/fasttext.py#L38 

`elems[0] = unicode(elems[0].decode('utf-8'))`

**Comment by gvishal** [comment]
Same goes for writing the modified vectors to file.

`out_line = token.encode('utf-8') + " " + vector_as_string + "\n"`

**Comment by nhammerla** [comment]
@gvishal Thank you for your interest in our work and your suggestions - glad you could make it work. Please note that we only support Python3, where this issue does not arise, as it has much improved unicode string handling compared with Python2.7. We will make it more explicit in the documentation to avoid confusion. That said - if you are keen then please put your changes in a PR!
