### ISSUE TITLE
Transform language embeddings in the same space as english.

### ISSUE THREAD

**Issue by gvishal** [Babylonpartners/fastText_multilingual#15]
I need to transform 'hi' (hindi) embeddings in the same space as english. For this do I run:

```
en_dictionary.apply_transform('alignment_matrices/en.txt')
hi_dictionary.apply_transform('alignment_matrices/hi.txt')
```

Or, do I only transform hi embeddings using:
```
hi_dictionary.apply_transform('alignment_matrices/hi.txt')
```

What is the significance of ```alignment_matrices/en.txt``` here? Since, from what I understand, the alignment matrices are used to transform a language embedding into the same space as english. So, what is the need for an alignment matrix for english?

**Comment by nhammerla** [comment]
@gvishal We just included the `en` matrix for completeness. It is just the diagonal identity matrix, so the `apply_transform('alignment_matrices/en.txt')` is actually not changing the vectors at all.

**Comment by gvishal** [comment]
Oh yeah, thanks!
