### ISSUE TITLE
The projection matrices are only compatible with the "txt" pretrained Facebook vectors and not with the "bin+txt" ones

### ISSUE THREAD

**Issue by neosyon** [Babylonpartners/fastText_multilingual#4]
I was doing some cross-lingual experiments from DE to EN and the results were really bad. Then I realized that the vectors provided by Facebook in "txt" are not the same as in "bin+txt" (at least for German). When I tried your matrices with the txt ones, it worked. Would it be possible to have also the projection matrices for the bin+txt version? The latter version is more useful if we need to extend the model with new word embeddings.

**Comment by Omarito2412** [comment]
I'm having the same problem with Arabic to English, FastText has released a new version recently (Probably new models) does that mean that the alignment matrices will be invalid for the new versions?

**Comment by sls56** [comment]
Hi @neosyon 

I just did a quick test on the Abkhazian bin/text files and the word vectors were the same in both, I would presume that this is true for all the languages. I'm afraid we only support loading the txt files, but the alignment matrices themselves should work for both.

I wonder if the issue arises because when you rotate the .bin file vectors, perhaps you only rotate the word vectors but not the ngram vectors. One potential dirty fix would be to rotate the vectors after inference rather than before. i.e., leave the bin file untouched, extract the vectors you want (for both in and out of vocabulary words), and then apply the matrix transformation to the word vectors generated by the bin file before comparison between languages.

**Comment by sls56** [comment]
@Omarito2412 the Facebook guys told us when they released extra languages that the word vectors for the original 90 languages did not change, they just added new ones. So if you are using the .txt files and data loader provided in this repository, it should work!

**Comment by neosyon** [comment]
Hi @sls56 

I tried again downloading again the French txt and txt+bin vectors. I did these searches:

` grep -w "python" ./txt/wiki.fr.vec

python -0.71198 0.28805 0.14268 0.36933 -0.31117 -0.047986 0.65574 0.18928 -0.50155 0.50775 -0.19401 0.37152 0.18625 0.16504 -0.50277 -0.065375 0.20438 0.070216 -0.24432 -0.16708 -0.0086874 -0.092192 0.10612 0.22314 0.069229 0.0066529 0.42445 -0.1812 0.67438 0.12485 -0.12772 0.44666 0.038536 0.092612 0.19019 0.058221 0.28089 -0.00024 0.61418 0.1535 -0.098631 0.32126 0.28123 0.12638 0.18749 -0.53231 0.124 0.64365 -0.30182 0.50859 0.61856 -0.1296 -0.27883 0.44989 0.50797 0.067944 -0.39739 -0.21764 -0.30415 -0.38301 -0.018366 -0.43741 -0.16612 -0.25305 -0.105 -0.38699 0.28668 0.3594 0.19464 0.11382 -0.23201 0.18414 -0.46276 0.050298 -0.78803 0.56793 0.12756 0.41792 -0.018451 0.25415 0.22147 -0.063021 0.35877 0.0404 -0.2568 -0.18902 0.34853 -0.28826 -0.11085 -0.47441 -0.44335 -0.17335 -0.063345 -0.7834 0.28612 0.23818 -0.11004 -0.20865 0.32956 -0.28867 -0.35629 -0.61507 0.13679 0.23588 0.12113 -0.036386 0.17194 0.20722 -0.20671 -0.35221 0.27746 0.10067 -0.59403 0.10697 0.14393 0.25009 0.22445 0.41969 0.27531 0.42527 -0.26388 0.053357 -0.45894 0.50365 0.25353 -0.58008 0.11811 -0.44895 0.75247 0.10532 -0.25091 0.024644 -0.16375 -0.31739 0.54434 0.026628 -0.19722 -0.053991 0.54591 0.084333 0.02914 0.03236 -0.49612 -0.19856 -0.20393 0.099609 -0.056535 -0.22963 0.27796 -0.5277 -0.021017 0.4755 -0.75469 -0.16008 0.075832 0.36915 0.28312 -0.36209 0.11729 0.067241 -0.45139 -0.34309 -0.025489 0.26301 0.32868 0.56259 0.32627 -0.41152 0.30271 0.2724 0.26249 -0.33536 0.38227 0.39154 -0.17725 -0.29222 0.24702 0.1492 0.2375 -0.61986 0.40236 0.1997 0.15922 -0.038641 0.16668 0.0091158 -0.0030147 0.40483 -0.012654 0.024824 -0.44614 0.048332 0.47368 0.055785 -0.036644 -0.10346 -0.10042 0.73235 -0.52879 0.1728 0.027918 -0.20349 -0.2248 -0.027757 -0.29851 0.11092 0.60911 -0.19693 -0.29161 -0.24299 -0.048943 0.0060964 0.47814 -0.28506 -0.032436 -0.33075 -0.099907 -0.52647 -0.22558 0.09241 -0.36791 0.2615 0.10751 -0.25228 -0.033512 -0.35543 -0.13818 -0.94252 -0.016812 0.059635 0.035275 0.17385 0.36898 0.095401 0.046161 0.13252 -0.030551 0.43725 0.21335 -0.20835 0.27085 0.055139 0.28204 0.31332 -0.66619 -0.17659 -0.18148 0.29778 0.20557 -0.16694 -0.46239 0.18539 0.12608 0.63442 -0.13156 -0.097099 0.093988 -0.027907 0.10945 0.064928 -0.0068127 -0.24888 0.51509 0.46613 0.14394 -0.37666 0.16395 -0.36942 -0.4207 0.37789 -0.11073 -0.34923 -0.191 0.3503 -0.47344 -0.16409 0.43099 0.083323 -0.12907 -0.6692 0.036717 -0.19491 -0.086738 0.0084066 0.42261 0.22319 0.54632 -0.5124 0.40881 -0.61305 0.44444 -0.23265 0.059009 -0.077005 0.15169 0.27707 -0.46189 0.48271 -0.0061517 0.24801`

` grep -w "python" ./txtPlusBin/wiki.fr.vec

python -0.18552 0.4517 -0.13564 -0.37235 0.51819 0.12612 -0.26173 -0.44776 -0.19934 0.25365 -0.0062502 -0.18307 0.13427 -0.66899 0.013655 0.41854 -0.46927 -0.013433 -0.15293 0.15131 -0.10014 -0.28402 -0.105 0.21081 -0.21942 -0.12016 0.035469 -0.11518 -0.69542 0.1565 -0.12853 0.30825 0.046473 -0.026791 -0.19413 -0.23644 -0.56997 -0.49036 0.67366 0.31093 -0.062078 0.21018 0.6358 0.25958 0.28475 -0.1139 0.14188 0.06328 0.3606 0.16431 0.13912 0.23863 0.29447 0.0081091 -0.31224 -0.31642 0.16316 -0.0012347 -0.23157 -0.38857 -0.1702 -0.24353 -0.038602 0.39952 0.23256 -0.63208 0.22642 -0.48661 -0.49322 -0.10116 0.085991 0.16415 -0.26734 -0.056575 -0.3747 -0.36683 0.50897 0.45071 0.35539 0.36735 0.26085 -0.31771 -0.2254 0.43676 -0.16187 0.20257 -0.54328 0.44171 -0.22331 0.15404 -0.1984 0.060215 0.56063 0.16894 0.46536 -0.024873 0.080183 -0.044522 -0.35691 0.46423 -0.029508 -0.20399 -0.25643 0.2827 0.21055 -0.08787 0.036692 -0.38022 0.36444 0.46727 -0.43002 -0.16944 -0.35283 0.3613 -0.62143 0.20752 -0.044101 -0.36202 -0.03261 0.49879 0.14211 -0.23855 -0.58988 0.096725 -0.38918 0.40613 0.62893 0.58025 -0.071545 -0.0052354 0.21365 0.17098 0.059733 0.12752 0.30109 -0.20272 -0.11343 0.36612 0.12687 -0.1535 0.041859 0.073799 -0.089208 0.26274 0.0028727 -0.15084 -0.22796 0.32062 0.35152 -0.015735 0.085512 0.063592 -0.45717 0.27398 -0.70866 0.31034 -0.080183 -0.067397 -0.056542 -0.04844 0.31571 0.02944 0.31778 0.24752 -0.1108 0.027057 0.06661 -0.31466 -0.20255 0.13225 0.35826 0.023502 0.042066 -0.1926 0.473 0.25006 0.0077495 -0.034498 0.12009 -0.83688 0.11065 -0.89116 0.091771 0.37779 0.20252 0.34875 0.058648 -0.14494 -0.47876 0.24643 -0.27304 -0.13565 0.25131 -0.30533 0.028002 -0.0040446 -0.054455 0.59454 -0.27535 0.30763 0.56603 -0.21526 0.065394 0.18571 -0.025369 0.18124 -0.17812 -0.33538 -0.17746 -0.010716 0.30261 0.41765 0.12634 -0.19444 0.26732 0.38849 0.56384 -0.69652 -0.15863 0.1398 -0.1617 -0.20664 -0.71493 0.23955 -0.63903 -0.19679 -0.0091641 -0.044683 -0.62398 -0.11041 0.22373 -0.13832 0.10072 0.13297 -0.28792 -0.20173 0.31636 0.051505 0.063848 -0.36832 -0.62469 -0.2151 0.031931 0.062207 -0.062098 -0.50413 0.024826 -0.10338 0.024731 -0.39111 -0.29673 -0.19395 0.36953 -0.2917 0.32803 -0.37989 -0.2716 -0.1101 -0.061263 0.74472 0.23597 -0.30489 0.40496 0.50595 -0.2294 0.23269 0.33501 0.54327 -0.37391 0.32701 -0.1822 -0.040683 -0.21561 -0.017939 -0.48629 -0.019429 -0.081526 0.043491 -0.55464 0.13648 -0.22602 -0.30188 -0.22804 -0.0972 -0.12659 -0.49659 0.12663 0.25624 0.80286 -0.1473 0.26848 -0.59206 0.40469 -0.047706 0.012481 0.19407 -0.22487 0.28884 0.13738 0.31129`

As you can see, these vectors are not equal.

**Comment by sls56** [comment]
@neosyon yep just checked this myself and my apologies you are correct!

For Abkhazian, I looked at a few words from both bin+text and text formats and these were all the same. But for French, the bin+text vectors are different to the text vectors; so clearly in general you can't assume these are the same. At the moment the transformations we provide in this repo only support the text format.

We will post an issue to the fastText repo and hopefully they will fix it! If they don't, we will upload transformations for both the bin and text formats.

Best,
Sam

**Comment by sls56** [comment]
@neosyon The Facebook guys have fixed the issue, and they say that all the models (in both formats) now correspond to the original vectors released.

I'll close the issue, let me know there are still problems...
